<?php

namespace TalkTalk\Core\Plugin;

use TalkTalk\Core\Plugin\PackingBehaviour\PluginPackerBehaviourInterface;
use TalkTalk\Core\ApplicationAware;

class UnpackedPlugin extends ApplicationAware
{

    protected static $packingBehaviours = array();
    protected static $packingBehavioursInitialized = false;

    public static function addBehaviour(PluginPackerBehaviourInterface $configHandler)
    {
        self::$packingBehaviours[] = $configHandler;
    }

    /**
     * @var string
     */
    public $path;
    /**
     * @var array
     */
    public $config;
    /**
     * @var array
     */
    public $pluginsPackingBehaviours = array();
    /**
     * @var string
     */
    public $id;

    /**
     * @return string
     */
    public function getPhpCodeToPack()
    {
        $code = '';

        // 1) Plugins packing behaviours init phase...
        // (this is in case of a Packer which would have something to do before others, like the NewPackersPacker)
        foreach(self::$packingBehaviours as $packingBehaviour) {
            $packingBehaviour->init($this);
        }

        // 1) Plugins packing behaviours packing phase!
        foreach(self::$packingBehaviours as $packingBehaviour)
        {
            $pluginPhpCodeForCurrentConfigHandler = $packingBehaviour->getPhpCodeToPack($this);

            if (null !== $pluginPhpCodeForCurrentConfigHandler) {
                $code .= PHP_EOL .
                    sprintf('/* Begin PHP code generated for plugin "%s" by Packing Behaviour "%s" */', $this->path, get_class($packingBehaviour)) . PHP_EOL .
                    $pluginPhpCodeForCurrentConfigHandler . PHP_EOL .
                    '/* End PHP code generated by Packing Behaviour "%s" */' . PHP_EOL
                ;
            }

        }

        return $code;
    }

    /**
     * @return array
     */
    public function getMetadataToPack()
    {
        $metadata = array();
        foreach(self::$packingBehaviours as $configHandler)
        {
            $pluginMetadataForCurrentConfigHandler = $configHandler->getMetadata($this);
            if (null !== $pluginMetadataForCurrentConfigHandler) {
                $metadata[] = $pluginMetadataForCurrentConfigHandler;
            }
        }

        return call_user_func_array('array_merge', $metadata);
    }

    public function getAppService($serviceId)
    {
        return $this->app->getService($serviceId);
    }

}